### ISSUE TITLE
AttributeError: module 'torch.nn' has no attribute 'L1SmoothLoss'

### ISSUE THREAD

**Issue by macromeer** [koopa31/napari_svetlana#1]
In the GUI, launching training with selected loss function _L1Smooth_ (all other parameters are default) results in an AttributeError with the message `"module 'torch.nn' has no attribute 'L1SmoothLoss'"`. The error arises from the following line of code:

`loss = eval("nn." + losses_dict[loss_func] + "().type(torch_type)")`

Variables at the time of the error:

`losses_dict = {'CrossEntropy': 'CrossEntropyLoss', 'L1Smooth': 'L1SmoothLoss', 'BCE': 'BceLoss', 'Distance': 'DistanceLoss', 'L1': 'L1_Loss', 'MSE': 'MseLoss'}`

`loss_func = 'L1Smooth'`

**Comment by koopa31** [comment]
Hi, 
Sorry for the delay, I'm gonna check it out.
Thank you for reporting

**Comment by koopa31** [comment]
it's corrected :)
